import zipfile
import os.path
import shutil
import os

try:
    import ipdb as pdb
except:
    import pdb

# path to target zip file
filePath = "/Users/Cheng/Documents/CRC projects/Projects/Cyber-Eye/newMatlabCodes2.0/Hawaii_data/newData2.0/data.zip"
targetPath = "/Users/Cheng/Documents/CRC projects/Projects/Cyber-Eye/newMatlabCodes2.0/Hawaii_data/newData2.0/"

# function to call. It will unzip the target zip file; create a folder in the same dir and save all the unzipped files in that folder.
# original zip file can be deleted thereafter
def unzipTarget(filePath, targetPath, verbosity=1):
    #pdb.set_trace()
    
    oldcwd = os.getcwd()
    # change working directory to target folder
    os.chdir(targetPath)
    
    # get dir and zip file name
    (dirname, filename) = os.path.split(filePath)
    # get zip file name and extension
    (filename, fileExtension) = os.path.splitext(filename)
    
    ## remove target unzipped folder if it already exists
    #zipfileFolder = os.path.join(dirname, filename)
    #if os.path.exists(zipfileFolder):
    #    shutil.rmtree(zipfileFolder)
    #os.makedirs(zipfileFolder)
    
    # extract binary file in zip one by one and then save them into target folder above       
    zfile = zipfile.ZipFile(filePath)
    for name in zfile.namelist():
        if verbosity > 0:
            print name
        
        # skip __MACOSX folders which generated by MAC system
        if not "__MACOSX" in name:
            if name.endswith('/'):
                os.makedirs(name)
            else:
                zfile.extract(name)
    
    os.chdir(oldcwd)

if __name__ == '__main__':
    # example how to call this function      
    unzipTarget(filePath, targetPath)    